const storeKey='ugMotionDataV2';
const demo={patients:[{id:'p1',name:'Carlos Ramírez',sport:'Fútbol',injury:'Rehab rodilla fase 2',created:new Date().toISOString()},{id:'p2',name:'Mariana Pérez',sport:'Atletismo',injury:'Isquios / retorno a carrera',created:new Date().toISOString()},{id:'p3',name:'Diego López',sport:'Básquetbol',injury:'Tobillo alto grado 2',created:new Date().toISOString()}],sessions:[{id:'s1',patientId:'p1',program:'Pierna – Fuerza',exercise:'Split squat búlgaro',load:'3x8 c/lado',rpePre:4,rpePost:7,notes:'Control de valgo y tempo.',date:new Date().toISOString()},{id:'s2',patientId:'p2',program:'Retorno carrera',exercise:'Nordic asistido',load:'3x5',rpePre:3,rpePost:6,notes:'Sin dolor posterior.',date:new Date().toISOString()}]};
let data=JSON.parse(localStorage.getItem(storeKey)||'null')||{patients:[],sessions:[]};
const exercises=[['Rodilla','Step down','Control excéntrico y alineación.'],['Isquios','Puente femoral','Fuerza posterior progresiva.'],['Hombro','Rotación externa','Control escapular y manguito.'],['Tobillo','Balance unipodal','Propiocepción y estabilidad.'],['Performance','Sentadilla trasera','Fuerza y control global.'],['Core','Dead bug','Estabilidad lumbopélvica.']];
function save(){localStorage.setItem(storeKey,JSON.stringify(data));render();}
function uid(){return crypto?.randomUUID?.()||String(Date.now()+Math.random())}
document.querySelectorAll('.nav-btn').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('.nav-btn,.view').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.getElementById(btn.dataset.view).classList.add('active');document.getElementById('viewTitle').textContent=btn.textContent;drawCharts();});
document.getElementById('seedBtn').onclick=()=>{data=structuredClone(demo);save();};
document.getElementById('patientForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.patients.unshift({id:uid(),name:f.get('name'),sport:f.get('sport'),injury:f.get('injury'),created:new Date().toISOString()});e.target.reset();save();};
document.getElementById('sessionForm').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target);data.sessions.unshift({id:uid(),patientId:f.get('patientId'),program:f.get('program'),exercise:f.get('exercise'),load:f.get('load'),rpePre:+f.get('rpePre'),rpePost:+f.get('rpePost'),notes:f.get('notes'),date:new Date().toISOString()});e.target.reset();save();};
function patientName(id){return data.patients.find(p=>p.id===id)?.name||'Sin paciente'}
function render(){document.getElementById('statPatients').textContent=data.patients.length;document.getElementById('statSessions').textContent=data.sessions.length;const avg=data.sessions.length?(data.sessions.reduce((a,s)=>a+s.rpePost,0)/data.sessions.length).toFixed(1):'-';document.getElementById('statRpe').textContent=avg;document.querySelector('#sessionForm select').innerHTML=data.patients.map(p=>`<option value="${p.id}">${p.name}</option>`).join('')||'<option>Primero agrega paciente</option>';document.getElementById('patientList').innerHTML=data.patients.map(p=>`<div class="item"><div><h3>${p.name}</h3><p>${p.sport} · ${p.injury}</p></div><span class="pill">Activo</span></div>`).join('')||'<div class="card">Aún no hay pacientes.</div>';document.getElementById('recentSessions').innerHTML=data.sessions.slice(0,6).map(s=>`<div class="item"><div><h3>${s.exercise}</h3><p>${patientName(s.patientId)} · ${s.program}<br>${s.load} · RPE ${s.rpePre} → ${s.rpePost}<br>${s.notes||''}</p></div><span class="pill">${new Date(s.date).toLocaleDateString()}</span></div>`).join('')||'<div class="card">Registra sesiones o carga el demo.</div>';document.getElementById('exerciseLibrary').innerHTML=exercises.map(e=>`<div class="card"><h3>${e[0]}</h3><strong>${e[1]}</strong><p>${e[2]}</p></div>`).join('');drawCharts();}
function chart(id,vals,label){const c=document.getElementById(id),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);ctx.strokeStyle='rgba(255,255,255,.12)';ctx.lineWidth=1;for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(40,i*h/5);ctx.lineTo(w-20,i*h/5);ctx.stroke()}ctx.fillStyle='#9aa4ad';ctx.font='24px system-ui';ctx.fillText(label,34,34);if(!vals.length)return;const max=Math.max(10,...vals),min=0;ctx.strokeStyle='#b8ff18';ctx.lineWidth=5;ctx.beginPath();vals.forEach((v,i)=>{const x=50+i*((w-90)/Math.max(vals.length-1,1));const y=h-35-((v-min)/(max-min))*(h-80);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle='#20e0ff';vals.forEach((v,i)=>{const x=50+i*((w-90)/Math.max(vals.length-1,1));const y=h-35-((v-min)/(max-min))*(h-80);ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill()})}
function drawCharts(){chart('rpeChart',data.sessions.slice().reverse().map(s=>s.rpePost),'RPE post sesión');chart('loadChart',data.sessions.slice().reverse().map((s,i)=>Number(String(s.load).match(/\d+/)?.[0]||i+1)),'Carga / volumen');}
let deferredPrompt;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;});document.getElementById('installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else{alert('En iPhone: abre esta app en Safari, toca Compartir y elige “Agregar a pantalla de inicio”.')}};
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));}
render();
